config {
    ENV_NAME = "dev"
    SNOWFLAKE_URL = credentials('SNOWFLAKE_URL')
    SNOWFLAKE_SCHEMA = "BALA"
    SNOWFLAKE_USER = credentials('SNOWFLAKE_USERNAME')
    SNOWFLAKE_PASSWORD = credentials('SNOWFLAKE_PASSWORD')
}