config {
    ENV_NAME = "uat"
    SNOWFLAKE_URL = credentials('SNOWFLAKE_URL')
    SNOWFLAKE_SCHEMA = "DEMO"
    SNOWFLAKE_USER = credentials('SNOWFLAKE_USERNAME')
    SNOWFLAKE_PASSWORD = credentials('SNOWFLAKE_PASSWORD')
}